export default {
    active: true,
    seed: 26,
    skyType: "gradient",
    skyColor: "#1b7660",
    horizonColor: "#e4b676",
    lighting: "distant",
    lightPosition: { x: 0, y: 1.65, z: -1 },
    fog: 0.75,
    flatShading: false,
    playArea: 1,
    ground: "hills",
    groundYScale: 5,
    groundTexture: "walkernoise",
    groundColor: "#664735",
    groundColor2: "#6c4b39",
    dressing: "pyramids",
    dressingAmount: 10,
    dressingColor: "#7c5c45",
    dressingScale: 5,
    dressingVariance: { x: 20, y: 20, z: 20 },
    dressingUniformScale: true,
    dressingOnPlayArea: 0,
    grid: "spots",
    gridColor: "#e4b676",
    shadow: false,
};
