export default {
    active: true,
    seed: 14,
    skyType: "gradient",
    skyColor: "#7e5db5",
    horizonColor: "#b4adda",
    lighting: "distant",
    lightPosition: { x: 1.33, y: 1, z: 0.24 },
    fog: 0.9,
    flatShading: false,
    playArea: 1,
    ground: "hills",
    groundYScale: 25,
    groundTexture: "walkernoise",
    groundColor: "#7e5db5",
    groundColor2: "#cabdf5",
    dressing: "torii",
    dressingAmount: 4,
    dressingColor: "#bc5e7c",
    dressingScale: 15,
    dressingVariance: { x: 0, y: 0, z: 0 },
    dressingUniformScale: true,
    dressingOnPlayArea: 0,
    grid: "spots",
    gridColor: "#e4b676",
    shadow: false,
};
