export default {
    active: true,
    seed: 46,
    skyType: "atmosphere",
    skyColor: "#88c",
    horizonColor: "#ddd",
    lighting: "distant",
    lightPosition: { x: 0, y: 0.02, z: -0.46 },
    fog: 0,
    flatShading: false,
    playArea: 1,
    ground: "hills",
    groundYScale: 3,
    groundTexture: "none",
    groundColor: "#9e7b47",
    groundColor2: "#9e7b47",
    dressing: "pyramids",
    dressingAmount: 7,
    dressingColor: "#9e7b47",
    dressingScale: 5,
    dressingVariance: { x: 30, y: 30, z: 30 },
    dressingUniformScale: true,
    grid: "dots",
    dressingOnPlayArea: 0,
    gridColor: "#daa452",
    shadow: false,
};
