export default {
    active: true,
    seed: 1,
    skyType: "atmosphere",
    skyColor: "#88c",
    horizonColor: "#ddd",
    lighting: "distant",
    lightPosition: { x: 0, y: -0.01, z: -0.46 },
    fog: 0.7,
    flatShading: false,
    playArea: 1,
    ground: "hills",
    groundYScale: 3,
    groundTexture: "none",
    groundColor: "#553e35",
    groundColor2: "#694439",
    dressing: "none",
    dressingAmount: 100,
    dressingColor: "#795449",
    dressingScale: 5,
    dressingVariance: { x: 1, y: 1, z: 1 },
    dressingUniformScale: true,
    grid: "1x1",
    dressingOnPlayArea: 0,
    gridColor: "#39d2f2",
    shadow: false,
};
